# Generated by Django 5.0.6 on 2024-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Visited', 'Visited'), ('Canceled', 'Canceled')], default='Booked', max_length=255),
        ),
    ]
